[package]
name = "gotham-example"
version = "0.1.0"
authors = ["Masaki Hara <ackie.h.gmai@gmail.com>"]

[dependencies]
mime = "0.3"
tokio = "0.1.5"
hyper = "0.11"
gotham = "0.2.1"
honeybadger = { path = ".." }
honeybadger-gotham = { path = "../honeybadger-gotham" }
