sudo: false
dist: trusty
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
env:
  - "MINVER=false"
  - "MINVER=true"
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  exclude:
    - rust: beta
      env: "MINVER=true"
    - rust: nightly
      env: "MINVER=true"
install:
  - rustup component add rustfmt-preview
script:
  - .travis/build.sh
