[package]
name = "honeybadger"
version = "0.1.0"
authors = ["Masaki Hara <ackie.h.gmai@gmail.com>"]
build = "build.rs"

[features]
rocket_hook = ["rocket"]

[dependencies]
lazy_static = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hyper = "0.11.25"
reqwest = "0.8.5"
backtrace = "0.3"
rustc_version_runtime = "0.1"

rocket = { version = "0.3", optional = true }
