[package]
name = "honeybadger"
description = "Honeybadger Notifier for Rust"
version = "0.1.0"
authors = ["Masaki Hara <ackie.h.gmai@gmail.com>"]
build = "build.rs"

homepage = "https://github.com/qnighy/honeybadger-rs"
repository = "https://github.com/qnighy/honeybadger-rs.git"
readme = "README.md"
keywords = ["honeybadger"]
categories = ["web-programming", "api-bindings", "development-tools"]
license = "MIT"

[dependencies]
lazy_static = "1.0"
rand = "0.4"
chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
failure = "0.1.1"
hyper = "0.11.25"
reqwest = "0.8.5"
rustc_version_runtime = "0.1"

[workspace]

members = [
  "honeybadger-rocket",
  "honeybadger-gotham",
  "rocket-example",
  "gotham-example",
]
