[package]
name = "rocket-example"
version = "0.1.0"
authors = ["Masaki Hara <ackie.h.gmai@gmail.com>"]

[dependencies]
rocket = "0.3.7"
rocket_codegen = "0.3.7"
honeybadger = { path = "..", features = ["rocket_hook"] }
